apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-app
    namespace: eks-demo-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: my-app
    template:
        metadata:
            labels:
                app: my-app
        spec:
            tolerations:
                - key: 'eks.amazonaws.com/compute-type'
                  operator: 'Equal'
                  value: 'fargate'
                  effect: 'NoSchedule'
            containers:
                - name: my-app-container
                  image: 872515275919.dkr.ecr.us-east-2.amazonaws.com/avionics-website:latest
                  ports:
                      - containerPort: 80
